-- AlterTable
ALTER TABLE `users` MODIFY `last_name` VARCHAR(191) NULL,
    MODIFY `phone_number` VARCHAR(191) NULL DEFAULT '+989120000000',
    MODIFY `role` ENUM('EMPLOYEE', 'MANAGER', 'DEVELOPER', 'CEO') NOT NULL DEFAULT 'EMPLOYEE',
    MODIFY `actions` JSON NULL,
    MODIFY `nickname` VARCHAR(191) NULL;
